apiVersion: v1
kind: Secret
metadata:
  name: pg-credentials
  namespace: default
type: Opaque
stringData:
  url: "postgres://postgres:mysecretpassword@postgres-service.default.svc.cluster.local:5432/?sslmode=disable"